/**
 * Manifest of classes that need to be required and where to find them. This
 * should be autogenerated. Allows fun things like requiring a namespace or a
 * class, instead of a file.
 */

/**
 * The contents of this object can be generated by the simple and easy to
 * understand command:
 *    find . -name "*.js" -print | xargs grep util.provide\(
 *        \ | sed s/:util.provide\(//
 *        \ | sed s:\./:\'\./:
 *        \ | sed s#\.js\'#\.js\':\ \'\#
 *        \ | sed s/\)\;/,/
 *
 * Same thing on one line for copying:
 * find . -name "*.js" -print | xargs grep util.provide\( | sed s/:util.provide\(// | sed s:\./:\'\./: | sed s#\.js\'#\.js\':\ \'\# | sed s/\)\;/,/
 */
var FILE_MANIFEST = {
'./app/data/producers/espy.js': 'dab.data.producers.Espy',
'./app/data/producers/gss.js': 'dab.data.producers.Gss',
'./app/data/registry.js': 'dab.data.Registry',
'./app/data/server.js': 'dab.data.Server',
'./app/data/store.js': 'dab.data.Store',
'./framework/module.js': 'cau.framework.ProducerModule',
'./framework/producer.js': 'cau.framework.Producer',
'./framework/registry.js': 'cau.framework.Registry',
'./framework/server.js': 'cau.framework.Server',
'./framework/store.js': 'cau.framework.Store',
}

module.exports = FILE_MANIFEST;